services:
  mongo:
    build: 
      context: './mongo'
      dockerfile: 'Dockerfile'
      args:
        MONGODB_VERSION: ${MONGODB_VERSION}
        MONGO_INITDB_DATABASE: ${DB_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - '${DATA_PATH_HOST}:/data/db'
    ports:
      - '${MONGODB_PORT}:27017'